name: Bump version, create tag
on:
  pull_request:
    branches:
      - main

jobs:
  bump_version:
    name: Bump version, create tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Bump version and push tag/create release point
        id: bump_version
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      - name: Repository dispatch tag created event
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          event-type: tag-created
          client-payload: '{"new_version": "${{ steps.bump_version.outputs.new_tag }}"}'